#!/usr/bin/env bash

MOCKS=(
    "contracts/hasher.go|mocks/hasher.go"
    "contracts/user_repository.go|mocks/user_repository.go"
    "contracts/user_service.go|mocks/user_service.go"
    "contracts/user_aggregator.go|mocks/user_aggregator.go"
    "contracts/user_api.go|mocks/user_api.go"
    "contracts/post_api.go|mocks/post_api.go"
)

for params in ${MOCKS[*]}
do
    IFS=$'|' read -r source destination <<< "$params"
    IFS=$'/' read -r package _ <<< "$destination"
    ~/go/bin/mockgen -source=${source} -destination=${destination} -package=${package}
done
