// Code generated by MockGen. DO NOT EDIT.
// Source: user_contract/user_repository.go

// Package user_mock is a generated GoMock package.
package user_mock

import (
	common "../common"
	user_domain "../user_domain"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUserRepository is a mock of UserRepository interface
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// ListUsers mocks base method
func (m *MockUserRepository) ListUsers() ([]*user_domain.UserEntity, common.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers")
	ret0, _ := ret[0].([]*user_domain.UserEntity)
	ret1, _ := ret[1].(common.Error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers
func (mr *MockUserRepositoryMockRecorder) ListUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserRepository)(nil).ListUsers))
}

// GetUser mocks base method
func (m *MockUserRepository) GetUser(userId *user_domain.UserId) (*user_domain.UserEntity, common.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", userId)
	ret0, _ := ret[0].(*user_domain.UserEntity)
	ret1, _ := ret[1].(common.Error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser
func (mr *MockUserRepositoryMockRecorder) GetUser(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserRepository)(nil).GetUser), userId)
}

// LookupUser mocks base method
func (m *MockUserRepository) LookupUser(userIdentity string) (*user_domain.UserEntity, common.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupUser", userIdentity)
	ret0, _ := ret[0].(*user_domain.UserEntity)
	ret1, _ := ret[1].(common.Error)
	return ret0, ret1
}

// LookupUser indicates an expected call of LookupUser
func (mr *MockUserRepositoryMockRecorder) LookupUser(userIdentity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupUser", reflect.TypeOf((*MockUserRepository)(nil).LookupUser), userIdentity)
}

// SaveUser mocks base method
func (m *MockUserRepository) SaveUser(userEntity *user_domain.UserEntity) common.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", userEntity)
	ret0, _ := ret[0].(common.Error)
	return ret0
}

// SaveUser indicates an expected call of SaveUser
func (mr *MockUserRepositoryMockRecorder) SaveUser(userEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockUserRepository)(nil).SaveUser), userEntity)
}

// RemoveUser mocks base method
func (m *MockUserRepository) RemoveUser(userEntity *user_domain.UserEntity) common.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUser", userEntity)
	ret0, _ := ret[0].(common.Error)
	return ret0
}

// RemoveUser indicates an expected call of RemoveUser
func (mr *MockUserRepositoryMockRecorder) RemoveUser(userEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUser", reflect.TypeOf((*MockUserRepository)(nil).RemoveUser), userEntity)
}
