// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/category_edges_builder_job.go

// Package mocks is a generated GoMock package.
package mocks

import (
	common "github.com/emelnychenko/go-press/common"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCategoryEdgesBuilderJob is a mock of CategoryEdgesBuilderJob interface
type MockCategoryEdgesBuilderJob struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryEdgesBuilderJobMockRecorder
}

// MockCategoryEdgesBuilderJobMockRecorder is the mock recorder for MockCategoryEdgesBuilderJob
type MockCategoryEdgesBuilderJobMockRecorder struct {
	mock *MockCategoryEdgesBuilderJob
}

// NewMockCategoryEdgesBuilderJob creates a new mock instance
func NewMockCategoryEdgesBuilderJob(ctrl *gomock.Controller) *MockCategoryEdgesBuilderJob {
	mock := &MockCategoryEdgesBuilderJob{ctrl: ctrl}
	mock.recorder = &MockCategoryEdgesBuilderJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCategoryEdgesBuilderJob) EXPECT() *MockCategoryEdgesBuilderJobMockRecorder {
	return m.recorder
}

// BuildCategoriesEdges mocks base method
func (m *MockCategoryEdgesBuilderJob) BuildCategoriesEdges() common.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildCategoriesEdges")
	ret0, _ := ret[0].(common.Error)
	return ret0
}

// BuildCategoriesEdges indicates an expected call of BuildCategoriesEdges
func (mr *MockCategoryEdgesBuilderJobMockRecorder) BuildCategoriesEdges() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildCategoriesEdges", reflect.TypeOf((*MockCategoryEdgesBuilderJob)(nil).BuildCategoriesEdges))
}
