// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/category_http_helper.go

// Package mocks is a generated GoMock package.
package mocks

import (
	common "github.com/emelnychenko/go-press/common"
	contracts "github.com/emelnychenko/go-press/contracts"
	models "github.com/emelnychenko/go-press/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCategoryHttpHelper is a mock of CategoryHttpHelper interface
type MockCategoryHttpHelper struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryHttpHelperMockRecorder
}

// MockCategoryHttpHelperMockRecorder is the mock recorder for MockCategoryHttpHelper
type MockCategoryHttpHelperMockRecorder struct {
	mock *MockCategoryHttpHelper
}

// NewMockCategoryHttpHelper creates a new mock instance
func NewMockCategoryHttpHelper(ctrl *gomock.Controller) *MockCategoryHttpHelper {
	mock := &MockCategoryHttpHelper{ctrl: ctrl}
	mock.recorder = &MockCategoryHttpHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCategoryHttpHelper) EXPECT() *MockCategoryHttpHelperMockRecorder {
	return m.recorder
}

// ParseCategoryId mocks base method
func (m *MockCategoryHttpHelper) ParseCategoryId(httpContext contracts.HttpContext) (*models.CategoryId, common.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseCategoryId", httpContext)
	ret0, _ := ret[0].(*models.CategoryId)
	ret1, _ := ret[1].(common.Error)
	return ret0, ret1
}

// ParseCategoryId indicates an expected call of ParseCategoryId
func (mr *MockCategoryHttpHelperMockRecorder) ParseCategoryId(httpContext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseCategoryId", reflect.TypeOf((*MockCategoryHttpHelper)(nil).ParseCategoryId), httpContext)
}
