// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/category_event_factory.go

// Package mocks is a generated GoMock package.
package mocks

import (
	contracts "github.com/emelnychenko/go-press/contracts"
	entities "github.com/emelnychenko/go-press/entities"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCategoryEventFactory is a mock of CategoryEventFactory interface
type MockCategoryEventFactory struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryEventFactoryMockRecorder
}

// MockCategoryEventFactoryMockRecorder is the mock recorder for MockCategoryEventFactory
type MockCategoryEventFactoryMockRecorder struct {
	mock *MockCategoryEventFactory
}

// NewMockCategoryEventFactory creates a new mock instance
func NewMockCategoryEventFactory(ctrl *gomock.Controller) *MockCategoryEventFactory {
	mock := &MockCategoryEventFactory{ctrl: ctrl}
	mock.recorder = &MockCategoryEventFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCategoryEventFactory) EXPECT() *MockCategoryEventFactoryMockRecorder {
	return m.recorder
}

// CreateCategoryCreatedEvent mocks base method
func (m *MockCategoryEventFactory) CreateCategoryCreatedEvent(categoryEntity *entities.CategoryEntity) contracts.CategoryEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategoryCreatedEvent", categoryEntity)
	ret0, _ := ret[0].(contracts.CategoryEvent)
	return ret0
}

// CreateCategoryCreatedEvent indicates an expected call of CreateCategoryCreatedEvent
func (mr *MockCategoryEventFactoryMockRecorder) CreateCategoryCreatedEvent(categoryEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategoryCreatedEvent", reflect.TypeOf((*MockCategoryEventFactory)(nil).CreateCategoryCreatedEvent), categoryEntity)
}

// CreateCategoryUpdatedEvent mocks base method
func (m *MockCategoryEventFactory) CreateCategoryUpdatedEvent(categoryEntity *entities.CategoryEntity) contracts.CategoryEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategoryUpdatedEvent", categoryEntity)
	ret0, _ := ret[0].(contracts.CategoryEvent)
	return ret0
}

// CreateCategoryUpdatedEvent indicates an expected call of CreateCategoryUpdatedEvent
func (mr *MockCategoryEventFactoryMockRecorder) CreateCategoryUpdatedEvent(categoryEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategoryUpdatedEvent", reflect.TypeOf((*MockCategoryEventFactory)(nil).CreateCategoryUpdatedEvent), categoryEntity)
}

// CreateCategoryDeletedEvent mocks base method
func (m *MockCategoryEventFactory) CreateCategoryDeletedEvent(categoryEntity *entities.CategoryEntity) contracts.CategoryEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategoryDeletedEvent", categoryEntity)
	ret0, _ := ret[0].(contracts.CategoryEvent)
	return ret0
}

// CreateCategoryDeletedEvent indicates an expected call of CreateCategoryDeletedEvent
func (mr *MockCategoryEventFactoryMockRecorder) CreateCategoryDeletedEvent(categoryEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategoryDeletedEvent", reflect.TypeOf((*MockCategoryEventFactory)(nil).CreateCategoryDeletedEvent), categoryEntity)
}
