// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/category_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "github.com/emelnychenko/go-press/entities"
	errors "github.com/emelnychenko/go-press/errors"
	models "github.com/emelnychenko/go-press/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCategoryService is a mock of CategoryService interface
type MockCategoryService struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryServiceMockRecorder
}

// MockCategoryServiceMockRecorder is the mock recorder for MockCategoryService
type MockCategoryServiceMockRecorder struct {
	mock *MockCategoryService
}

// NewMockCategoryService creates a new mock instance
func NewMockCategoryService(ctrl *gomock.Controller) *MockCategoryService {
	mock := &MockCategoryService{ctrl: ctrl}
	mock.recorder = &MockCategoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCategoryService) EXPECT() *MockCategoryServiceMockRecorder {
	return m.recorder
}

// ListCategories mocks base method
func (m *MockCategoryService) ListCategories(categoryPaginationQuery *models.CategoryPaginationQuery) (*models.PaginationResult, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", categoryPaginationQuery)
	ret0, _ := ret[0].(*models.PaginationResult)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories
func (mr *MockCategoryServiceMockRecorder) ListCategories(categoryPaginationQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockCategoryService)(nil).ListCategories), categoryPaginationQuery)
}

// GetCategoriesTree mocks base method
func (m *MockCategoryService) GetCategoriesTree() (*entities.CategoryEntityTree, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoriesTree")
	ret0, _ := ret[0].(*entities.CategoryEntityTree)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetCategoriesTree indicates an expected call of GetCategoriesTree
func (mr *MockCategoryServiceMockRecorder) GetCategoriesTree() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoriesTree", reflect.TypeOf((*MockCategoryService)(nil).GetCategoriesTree))
}

// GetCategory mocks base method
func (m *MockCategoryService) GetCategory(categoryId *models.CategoryId) (*entities.CategoryEntity, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", categoryId)
	ret0, _ := ret[0].(*entities.CategoryEntity)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory
func (mr *MockCategoryServiceMockRecorder) GetCategory(categoryId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockCategoryService)(nil).GetCategory), categoryId)
}

// GetCategoryTree mocks base method
func (m *MockCategoryService) GetCategoryTree(categoryId *models.CategoryId) (*entities.CategoryEntityTree, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryTree", categoryId)
	ret0, _ := ret[0].(*entities.CategoryEntityTree)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetCategoryTree indicates an expected call of GetCategoryTree
func (mr *MockCategoryServiceMockRecorder) GetCategoryTree(categoryId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryTree", reflect.TypeOf((*MockCategoryService)(nil).GetCategoryTree), categoryId)
}

// CreateCategory mocks base method
func (m *MockCategoryService) CreateCategory(data *models.CategoryCreate) (*entities.CategoryEntity, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", data)
	ret0, _ := ret[0].(*entities.CategoryEntity)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory
func (mr *MockCategoryServiceMockRecorder) CreateCategory(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockCategoryService)(nil).CreateCategory), data)
}

// UpdateCategory mocks base method
func (m *MockCategoryService) UpdateCategory(categoryEntity *entities.CategoryEntity, data *models.CategoryUpdate) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", categoryEntity, data)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory
func (mr *MockCategoryServiceMockRecorder) UpdateCategory(categoryEntity, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockCategoryService)(nil).UpdateCategory), categoryEntity, data)
}

// ChangeCategoryParent mocks base method
func (m *MockCategoryService) ChangeCategoryParent(categoryEntity, parentCategoryEntity *entities.CategoryEntity) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeCategoryParent", categoryEntity, parentCategoryEntity)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// ChangeCategoryParent indicates an expected call of ChangeCategoryParent
func (mr *MockCategoryServiceMockRecorder) ChangeCategoryParent(categoryEntity, parentCategoryEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeCategoryParent", reflect.TypeOf((*MockCategoryService)(nil).ChangeCategoryParent), categoryEntity, parentCategoryEntity)
}

// RemoveCategoryParent mocks base method
func (m *MockCategoryService) RemoveCategoryParent(categoryEntity *entities.CategoryEntity) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCategoryParent", categoryEntity)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// RemoveCategoryParent indicates an expected call of RemoveCategoryParent
func (mr *MockCategoryServiceMockRecorder) RemoveCategoryParent(categoryEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCategoryParent", reflect.TypeOf((*MockCategoryService)(nil).RemoveCategoryParent), categoryEntity)
}

// DeleteCategory mocks base method
func (m *MockCategoryService) DeleteCategory(categoryEntity *entities.CategoryEntity) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", categoryEntity)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory
func (mr *MockCategoryServiceMockRecorder) DeleteCategory(categoryEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockCategoryService)(nil).DeleteCategory), categoryEntity)
}

// GetCategoryXrefs mocks base method
func (m *MockCategoryService) GetCategoryXrefs(arg0 *entities.CategoryEntity) ([]*entities.CategoryXrefEntity, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryXrefs", arg0)
	ret0, _ := ret[0].([]*entities.CategoryXrefEntity)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetCategoryXrefs indicates an expected call of GetCategoryXrefs
func (mr *MockCategoryServiceMockRecorder) GetCategoryXrefs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryXrefs", reflect.TypeOf((*MockCategoryService)(nil).GetCategoryXrefs), arg0)
}

// GetCategoryObjectXrefs mocks base method
func (m *MockCategoryService) GetCategoryObjectXrefs(arg0 models.Object) ([]*entities.CategoryXrefEntity, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryObjectXrefs", arg0)
	ret0, _ := ret[0].([]*entities.CategoryXrefEntity)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetCategoryObjectXrefs indicates an expected call of GetCategoryObjectXrefs
func (mr *MockCategoryServiceMockRecorder) GetCategoryObjectXrefs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryObjectXrefs", reflect.TypeOf((*MockCategoryService)(nil).GetCategoryObjectXrefs), arg0)
}

// GetCategoryXref mocks base method
func (m *MockCategoryService) GetCategoryXref(arg0 *entities.CategoryEntity, arg1 models.Object) (*entities.CategoryXrefEntity, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryXref", arg0, arg1)
	ret0, _ := ret[0].(*entities.CategoryXrefEntity)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetCategoryXref indicates an expected call of GetCategoryXref
func (mr *MockCategoryServiceMockRecorder) GetCategoryXref(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryXref", reflect.TypeOf((*MockCategoryService)(nil).GetCategoryXref), arg0, arg1)
}

// CreateCategoryXref mocks base method
func (m *MockCategoryService) CreateCategoryXref(arg0 *entities.CategoryEntity, arg1 models.Object) (*entities.CategoryXrefEntity, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategoryXref", arg0, arg1)
	ret0, _ := ret[0].(*entities.CategoryXrefEntity)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// CreateCategoryXref indicates an expected call of CreateCategoryXref
func (mr *MockCategoryServiceMockRecorder) CreateCategoryXref(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategoryXref", reflect.TypeOf((*MockCategoryService)(nil).CreateCategoryXref), arg0, arg1)
}

// DeleteCategoryXref mocks base method
func (m *MockCategoryService) DeleteCategoryXref(arg0 *entities.CategoryXrefEntity) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategoryXref", arg0)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// DeleteCategoryXref indicates an expected call of DeleteCategoryXref
func (mr *MockCategoryServiceMockRecorder) DeleteCategoryXref(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategoryXref", reflect.TypeOf((*MockCategoryService)(nil).DeleteCategoryXref), arg0)
}
