// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/category_entity_factory.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "github.com/emelnychenko/go-press/entities"
	models "github.com/emelnychenko/go-press/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCategoryEntityFactory is a mock of CategoryEntityFactory interface
type MockCategoryEntityFactory struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryEntityFactoryMockRecorder
}

// MockCategoryEntityFactoryMockRecorder is the mock recorder for MockCategoryEntityFactory
type MockCategoryEntityFactoryMockRecorder struct {
	mock *MockCategoryEntityFactory
}

// NewMockCategoryEntityFactory creates a new mock instance
func NewMockCategoryEntityFactory(ctrl *gomock.Controller) *MockCategoryEntityFactory {
	mock := &MockCategoryEntityFactory{ctrl: ctrl}
	mock.recorder = &MockCategoryEntityFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCategoryEntityFactory) EXPECT() *MockCategoryEntityFactoryMockRecorder {
	return m.recorder
}

// CreateCategoryEntity mocks base method
func (m *MockCategoryEntityFactory) CreateCategoryEntity() *entities.CategoryEntity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategoryEntity")
	ret0, _ := ret[0].(*entities.CategoryEntity)
	return ret0
}

// CreateCategoryEntity indicates an expected call of CreateCategoryEntity
func (mr *MockCategoryEntityFactoryMockRecorder) CreateCategoryEntity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategoryEntity", reflect.TypeOf((*MockCategoryEntityFactory)(nil).CreateCategoryEntity))
}

// CreateCategoryXrefEntity mocks base method
func (m *MockCategoryEntityFactory) CreateCategoryXrefEntity(arg0 *entities.CategoryEntity, arg1 models.Object) *entities.CategoryXrefEntity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategoryXrefEntity", arg0, arg1)
	ret0, _ := ret[0].(*entities.CategoryXrefEntity)
	return ret0
}

// CreateCategoryXrefEntity indicates an expected call of CreateCategoryXrefEntity
func (mr *MockCategoryEntityFactoryMockRecorder) CreateCategoryXrefEntity(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategoryXrefEntity", reflect.TypeOf((*MockCategoryEntityFactory)(nil).CreateCategoryXrefEntity), arg0, arg1)
}
