// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/file_entity_factory.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "github.com/emelnychenko/go-press/entities"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockFileEntityFactory is a mock of FileEntityFactory interface
type MockFileEntityFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFileEntityFactoryMockRecorder
}

// MockFileEntityFactoryMockRecorder is the mock recorder for MockFileEntityFactory
type MockFileEntityFactoryMockRecorder struct {
	mock *MockFileEntityFactory
}

// NewMockFileEntityFactory creates a new mock instance
func NewMockFileEntityFactory(ctrl *gomock.Controller) *MockFileEntityFactory {
	mock := &MockFileEntityFactory{ctrl: ctrl}
	mock.recorder = &MockFileEntityFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFileEntityFactory) EXPECT() *MockFileEntityFactoryMockRecorder {
	return m.recorder
}

// CreateFileEntity mocks base method
func (m *MockFileEntityFactory) CreateFileEntity() *entities.FileEntity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFileEntity")
	ret0, _ := ret[0].(*entities.FileEntity)
	return ret0
}

// CreateFileEntity indicates an expected call of CreateFileEntity
func (mr *MockFileEntityFactoryMockRecorder) CreateFileEntity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFileEntity", reflect.TypeOf((*MockFileEntityFactory)(nil).CreateFileEntity))
}
