// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/post_category_api.go

// Package mocks is a generated GoMock package.
package mocks

import (
	errors "github.com/emelnychenko/go-press/errors"
	models "github.com/emelnychenko/go-press/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPostCategoryApi is a mock of PostCategoryApi interface
type MockPostCategoryApi struct {
	ctrl     *gomock.Controller
	recorder *MockPostCategoryApiMockRecorder
}

// MockPostCategoryApiMockRecorder is the mock recorder for MockPostCategoryApi
type MockPostCategoryApiMockRecorder struct {
	mock *MockPostCategoryApi
}

// NewMockPostCategoryApi creates a new mock instance
func NewMockPostCategoryApi(ctrl *gomock.Controller) *MockPostCategoryApi {
	mock := &MockPostCategoryApi{ctrl: ctrl}
	mock.recorder = &MockPostCategoryApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPostCategoryApi) EXPECT() *MockPostCategoryApiMockRecorder {
	return m.recorder
}

// ListPostCategories mocks base method
func (m *MockPostCategoryApi) ListPostCategories(arg0 *models.PostId, arg1 *models.CategoryPaginationQuery) (*models.PaginationResult, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPostCategories", arg0, arg1)
	ret0, _ := ret[0].(*models.PaginationResult)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// ListPostCategories indicates an expected call of ListPostCategories
func (mr *MockPostCategoryApiMockRecorder) ListPostCategories(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPostCategories", reflect.TypeOf((*MockPostCategoryApi)(nil).ListPostCategories), arg0, arg1)
}

// AddPostCategory mocks base method
func (m *MockPostCategoryApi) AddPostCategory(arg0 *models.PostId, arg1 *models.CategoryId) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPostCategory", arg0, arg1)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// AddPostCategory indicates an expected call of AddPostCategory
func (mr *MockPostCategoryApiMockRecorder) AddPostCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPostCategory", reflect.TypeOf((*MockPostCategoryApi)(nil).AddPostCategory), arg0, arg1)
}

// RemovePostCategory mocks base method
func (m *MockPostCategoryApi) RemovePostCategory(arg0 *models.PostId, arg1 *models.CategoryId) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePostCategory", arg0, arg1)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// RemovePostCategory indicates an expected call of RemovePostCategory
func (mr *MockPostCategoryApiMockRecorder) RemovePostCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePostCategory", reflect.TypeOf((*MockPostCategoryApi)(nil).RemovePostCategory), arg0, arg1)
}
