// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/post_tag_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "github.com/emelnychenko/go-press/entities"
	errors "github.com/emelnychenko/go-press/errors"
	models "github.com/emelnychenko/go-press/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPostTagService is a mock of PostTagService interface
type MockPostTagService struct {
	ctrl     *gomock.Controller
	recorder *MockPostTagServiceMockRecorder
}

// MockPostTagServiceMockRecorder is the mock recorder for MockPostTagService
type MockPostTagServiceMockRecorder struct {
	mock *MockPostTagService
}

// NewMockPostTagService creates a new mock instance
func NewMockPostTagService(ctrl *gomock.Controller) *MockPostTagService {
	mock := &MockPostTagService{ctrl: ctrl}
	mock.recorder = &MockPostTagServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPostTagService) EXPECT() *MockPostTagServiceMockRecorder {
	return m.recorder
}

// ListPostTags mocks base method
func (m *MockPostTagService) ListPostTags(arg0 *entities.PostEntity, arg1 *models.TagPaginationQuery) (*models.PaginationResult, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPostTags", arg0, arg1)
	ret0, _ := ret[0].(*models.PaginationResult)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// ListPostTags indicates an expected call of ListPostTags
func (mr *MockPostTagServiceMockRecorder) ListPostTags(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPostTags", reflect.TypeOf((*MockPostTagService)(nil).ListPostTags), arg0, arg1)
}

// AddPostTag mocks base method
func (m *MockPostTagService) AddPostTag(arg0 *entities.PostEntity, arg1 *entities.TagEntity) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPostTag", arg0, arg1)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// AddPostTag indicates an expected call of AddPostTag
func (mr *MockPostTagServiceMockRecorder) AddPostTag(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPostTag", reflect.TypeOf((*MockPostTagService)(nil).AddPostTag), arg0, arg1)
}

// RemovePostTag mocks base method
func (m *MockPostTagService) RemovePostTag(arg0 *entities.PostEntity, arg1 *entities.TagEntity) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePostTag", arg0, arg1)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// RemovePostTag indicates an expected call of RemovePostTag
func (mr *MockPostTagServiceMockRecorder) RemovePostTag(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePostTag", reflect.TypeOf((*MockPostTagService)(nil).RemovePostTag), arg0, arg1)
}
