// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/tag_entity_factory.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "github.com/emelnychenko/go-press/entities"
	models "github.com/emelnychenko/go-press/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockTagEntityFactory is a mock of TagEntityFactory interface
type MockTagEntityFactory struct {
	ctrl     *gomock.Controller
	recorder *MockTagEntityFactoryMockRecorder
}

// MockTagEntityFactoryMockRecorder is the mock recorder for MockTagEntityFactory
type MockTagEntityFactoryMockRecorder struct {
	mock *MockTagEntityFactory
}

// NewMockTagEntityFactory creates a new mock instance
func NewMockTagEntityFactory(ctrl *gomock.Controller) *MockTagEntityFactory {
	mock := &MockTagEntityFactory{ctrl: ctrl}
	mock.recorder = &MockTagEntityFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTagEntityFactory) EXPECT() *MockTagEntityFactoryMockRecorder {
	return m.recorder
}

// CreateTagEntity mocks base method
func (m *MockTagEntityFactory) CreateTagEntity() *entities.TagEntity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTagEntity")
	ret0, _ := ret[0].(*entities.TagEntity)
	return ret0
}

// CreateTagEntity indicates an expected call of CreateTagEntity
func (mr *MockTagEntityFactoryMockRecorder) CreateTagEntity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTagEntity", reflect.TypeOf((*MockTagEntityFactory)(nil).CreateTagEntity))
}

// CreateTagXrefEntity mocks base method
func (m *MockTagEntityFactory) CreateTagXrefEntity(arg0 *entities.TagEntity, arg1 models.Object) *entities.TagXrefEntity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTagXrefEntity", arg0, arg1)
	ret0, _ := ret[0].(*entities.TagXrefEntity)
	return ret0
}

// CreateTagXrefEntity indicates an expected call of CreateTagXrefEntity
func (mr *MockTagEntityFactoryMockRecorder) CreateTagXrefEntity(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTagXrefEntity", reflect.TypeOf((*MockTagEntityFactory)(nil).CreateTagXrefEntity), arg0, arg1)
}
