// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/tag_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "github.com/emelnychenko/go-press/entities"
	errors "github.com/emelnychenko/go-press/errors"
	models "github.com/emelnychenko/go-press/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockTagRepository is a mock of TagRepository interface
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// ListTags mocks base method
func (m *MockTagRepository) ListTags(tagPaginationQuery *models.TagPaginationQuery) (*models.PaginationResult, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", tagPaginationQuery)
	ret0, _ := ret[0].(*models.PaginationResult)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags
func (mr *MockTagRepositoryMockRecorder) ListTags(tagPaginationQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockTagRepository)(nil).ListTags), tagPaginationQuery)
}

// GetTag mocks base method
func (m *MockTagRepository) GetTag(tagId *models.TagId) (*entities.TagEntity, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTag", tagId)
	ret0, _ := ret[0].(*entities.TagEntity)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetTag indicates an expected call of GetTag
func (mr *MockTagRepositoryMockRecorder) GetTag(tagId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTag", reflect.TypeOf((*MockTagRepository)(nil).GetTag), tagId)
}

// SaveTag mocks base method
func (m *MockTagRepository) SaveTag(tagEntity *entities.TagEntity) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTag", tagEntity)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// SaveTag indicates an expected call of SaveTag
func (mr *MockTagRepositoryMockRecorder) SaveTag(tagEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTag", reflect.TypeOf((*MockTagRepository)(nil).SaveTag), tagEntity)
}

// RemoveTag mocks base method
func (m *MockTagRepository) RemoveTag(tagEntity *entities.TagEntity) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTag", tagEntity)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// RemoveTag indicates an expected call of RemoveTag
func (mr *MockTagRepositoryMockRecorder) RemoveTag(tagEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTag", reflect.TypeOf((*MockTagRepository)(nil).RemoveTag), tagEntity)
}

// GetTagXrefs mocks base method
func (m *MockTagRepository) GetTagXrefs(arg0 *entities.TagEntity) ([]*entities.TagXrefEntity, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagXrefs", arg0)
	ret0, _ := ret[0].([]*entities.TagXrefEntity)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetTagXrefs indicates an expected call of GetTagXrefs
func (mr *MockTagRepositoryMockRecorder) GetTagXrefs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagXrefs", reflect.TypeOf((*MockTagRepository)(nil).GetTagXrefs), arg0)
}

// GetTagObjectXrefs mocks base method
func (m *MockTagRepository) GetTagObjectXrefs(arg0 models.Object) ([]*entities.TagXrefEntity, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagObjectXrefs", arg0)
	ret0, _ := ret[0].([]*entities.TagXrefEntity)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetTagObjectXrefs indicates an expected call of GetTagObjectXrefs
func (mr *MockTagRepositoryMockRecorder) GetTagObjectXrefs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagObjectXrefs", reflect.TypeOf((*MockTagRepository)(nil).GetTagObjectXrefs), arg0)
}

// GetTagXref mocks base method
func (m *MockTagRepository) GetTagXref(arg0 *entities.TagEntity, arg1 models.Object) (*entities.TagXrefEntity, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagXref", arg0, arg1)
	ret0, _ := ret[0].(*entities.TagXrefEntity)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetTagXref indicates an expected call of GetTagXref
func (mr *MockTagRepositoryMockRecorder) GetTagXref(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagXref", reflect.TypeOf((*MockTagRepository)(nil).GetTagXref), arg0, arg1)
}

// SaveTagXref mocks base method
func (m *MockTagRepository) SaveTagXref(arg0 *entities.TagXrefEntity) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTagXref", arg0)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// SaveTagXref indicates an expected call of SaveTagXref
func (mr *MockTagRepositoryMockRecorder) SaveTagXref(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTagXref", reflect.TypeOf((*MockTagRepository)(nil).SaveTagXref), arg0)
}

// RemoveTagXref mocks base method
func (m *MockTagRepository) RemoveTagXref(arg0 *entities.TagXrefEntity) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTagXref", arg0)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// RemoveTagXref indicates an expected call of RemoveTagXref
func (mr *MockTagRepositoryMockRecorder) RemoveTagXref(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTagXref", reflect.TypeOf((*MockTagRepository)(nil).RemoveTagXref), arg0)
}
