// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/user_picture_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "github.com/emelnychenko/go-press/entities"
	errors "github.com/emelnychenko/go-press/errors"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUserPictureService is a mock of UserPictureService interface
type MockUserPictureService struct {
	ctrl     *gomock.Controller
	recorder *MockUserPictureServiceMockRecorder
}

// MockUserPictureServiceMockRecorder is the mock recorder for MockUserPictureService
type MockUserPictureServiceMockRecorder struct {
	mock *MockUserPictureService
}

// NewMockUserPictureService creates a new mock instance
func NewMockUserPictureService(ctrl *gomock.Controller) *MockUserPictureService {
	mock := &MockUserPictureService{ctrl: ctrl}
	mock.recorder = &MockUserPictureServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserPictureService) EXPECT() *MockUserPictureServiceMockRecorder {
	return m.recorder
}

// ChangeUserPicture mocks base method
func (m *MockUserPictureService) ChangeUserPicture(userEntity *entities.UserEntity, userPictureEntity *entities.FileEntity) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserPicture", userEntity, userPictureEntity)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// ChangeUserPicture indicates an expected call of ChangeUserPicture
func (mr *MockUserPictureServiceMockRecorder) ChangeUserPicture(userEntity, userPictureEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserPicture", reflect.TypeOf((*MockUserPictureService)(nil).ChangeUserPicture), userEntity, userPictureEntity)
}

// RemoveUserPicture mocks base method
func (m *MockUserPictureService) RemoveUserPicture(userEntity *entities.UserEntity) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserPicture", userEntity)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// RemoveUserPicture indicates an expected call of RemoveUserPicture
func (mr *MockUserPictureServiceMockRecorder) RemoveUserPicture(userEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserPicture", reflect.TypeOf((*MockUserPictureService)(nil).RemoveUserPicture), userEntity)
}
