// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/user_aggregator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "github.com/emelnychenko/go-press/entities"
	models "github.com/emelnychenko/go-press/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUserAggregator is a mock of UserAggregator interface
type MockUserAggregator struct {
	ctrl     *gomock.Controller
	recorder *MockUserAggregatorMockRecorder
}

// MockUserAggregatorMockRecorder is the mock recorder for MockUserAggregator
type MockUserAggregatorMockRecorder struct {
	mock *MockUserAggregator
}

// NewMockUserAggregator creates a new mock instance
func NewMockUserAggregator(ctrl *gomock.Controller) *MockUserAggregator {
	mock := &MockUserAggregator{ctrl: ctrl}
	mock.recorder = &MockUserAggregatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserAggregator) EXPECT() *MockUserAggregatorMockRecorder {
	return m.recorder
}

// AggregateUser mocks base method
func (m *MockUserAggregator) AggregateUser(object *entities.UserEntity) *models.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateUser", object)
	ret0, _ := ret[0].(*models.User)
	return ret0
}

// AggregateUser indicates an expected call of AggregateUser
func (mr *MockUserAggregatorMockRecorder) AggregateUser(object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateUser", reflect.TypeOf((*MockUserAggregator)(nil).AggregateUser), object)
}

// AggregateUsers mocks base method
func (m *MockUserAggregator) AggregateUsers(collection []*entities.UserEntity) []*models.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateUsers", collection)
	ret0, _ := ret[0].([]*models.User)
	return ret0
}

// AggregateUsers indicates an expected call of AggregateUsers
func (mr *MockUserAggregatorMockRecorder) AggregateUsers(collection interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateUsers", reflect.TypeOf((*MockUserAggregator)(nil).AggregateUsers), collection)
}
